# Basic colors
foreground              #F3EDF7
background              #0B0B2B
selection_foreground    #0B0B2B
selection_background    #F3EDF7

# Cursor
cursor                  #FFF59B
cursor_text_color       #070722
cursor_trail_color      #7C80B4

# URLs
url_color               #FFF59B

# Kitty window borders
active_border_color     #FFF59B
inactive_border_color   #11112D
bell_border_color       #FD4663

# OS window titlebar
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar
active_tab_foreground   #0E0E43
active_tab_background   #FFF59B
inactive_tab_foreground #A9AEEF
inactive_tab_background #11112D
tab_bar_background      #070722

# Marks
mark1_foreground #0B0B2B
mark1_background #A9AEEF
mark2_foreground #0B0B2B
mark2_background #FD4663
mark3_foreground #0B0B2B
mark3_background #9BF ECE

# 16 terminal colors

# Black
color0  #11112D
color8  #21215F

# Red
color1  #FD4663
color9  #FF5C78

# Green
color2  #9BFECE
color10 #B0FFDA

# Yellow
color3  #FFF59B
color11 #FFF7B8

# Blue
color4  #A9AEEF
color12 #BEC2FF

# Magenta
color5  #FD4663
color13 #FF6680

# Cyan
color6  #9BFECE
color14 #B0FFDA

# White
color7  #F3EDF7
color15 #FFFFFF
